name: build

on:
  push:
    branches: ["main"]

env:
  STACKROX_CENTRAL_HOST: central-stackrox.apps.cluster-sj5vt.sj5vt.sandbox1671.opentlc.com
  ROX_API_TOKEN: eyJhbGciOiJSUzI1NiIsImtpZCI6Imp3dGswIiwidHlwIjoiSldUIn0.eyJFeHBpcmVBdCI6bnVsbCwiYXVkIjoiaHR0cHM6Ly9zdGFja3JveC5pby9qd3Qtc291cmNlcyNhcGktdG9rZW5zIiwiZXhwIjoxNzc3NTA0MTYxLCJpYXQiOjE3NDU5NjgxNjEsImlzcyI6Imh0dHBzOi8vc3RhY2tyb3guaW8vand0IiwianRpIjoiNGMwOTE3Y2MtOGE5Yi00NjQ3LWE2NDMtYzdhYmJmYjNkY2M0IiwibmFtZSI6InRva2VuLW9wZW5zaGlmdC1waXBlbGluZXMiLCJyb2xlcyI6WyJDb250aW51b3VzIEludGVncmF0aW9uIl19.OGGvXlCKvk6BcmPt_B9Eh14Hq2rYDPr7CtcLXtYw1SEPHCo_HkTZcfBPWqUySZYLyEkXCVSdhH5lOF0Zx922lPal9JJTTwoAPPyEbtMLREt5TjmwrGlZVHJOqwsBZkTPhm8o4htq6b_5CcqZFxQkRx3t-QX_-mMs_v2uld9wY3Pa5WEoI2T3dIV_oH33UpjkwUDEYYedsAh-raieObZrJ3xnaixjnpQF7kuhXO0mspIJdV1cozCwCyhtdXcG-GYagyT8uIbQmgA2kkW7Dd6tbh9-UnibObIk4dlDRUInhbVsBTy2578eOeIjNfx5Sh73kNUneT8ijpkPzNt81f7jtY0BnPHRbH8J-Fmrf40AIbQ69aa3BTc8itOAmwSAnWiYtTgsrpr2IQ4nGxCOtmR4dJexUVQhYHJIeixNzpDeOEOPgOyPMR7-P4Tufd0slAuHngqCYAAx0lM62JbPoKNutq9_y0zZl_TDk_AGv21WOWMnbLcihrBalphzuqFdH69Dpr7rWxqzYJj89RFg6gintsDXo1-qaN5qjk2ojuvxsbKAVxfy8zoE13mgY4ZFNFztUig4_NG90Wet2lmab3kZzR0gjaJXfPmC-fqa2-65laTiVzXr4reoie1Qc0YftM7rIawCfoTXyEkXGVPP3CuGuS9UD7gbk650_CtWxF4XuIg
  QUAY_IO_REPOSITORY: quay.io/doliveira1277/pipeline-acs
  QUAY_IO_USERNAME: ${{ secrets.QUAY_IO_USERNAME }}
  QUAY_IO_PASSWORD: ${{ secrets.QUAY_IO_PASSWORD }}

jobs:
  build-image:
    runs-on: ["ubuntu-24.04"]
    steps:
    - uses: actions/checkout@v3
    - name: install roxctl
      run: |
            curl -k -H "Authorization: Bearer $ROX_API_TOKEN" https://$STACKROX_CENTRAL_HOST:443/api/cli/download/roxctl-linux -o roxctl && chmod +x ./roxctl

    - name: set image tag
      id: set-tag
      run: |
          DATE=$(date +'%Y%m%d')
          TAG="${DATE}${GITHUB_RUN_NUMBER}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT    
    
    - name: Podman build image
      run: |
          podman build -t $QUAY_IO_REPOSITORY:${{ steps.set-tag.outputs.tag }} . -f app/Dockerfile

    - name: Podman push image
      run: |
          podman login -u="$QUAY_IO_USERNAME" -p="$QUAY_IO_PASSWORD" quay.io
          podman push $QUAY_IO_REPOSITORY:${{ steps.set-tag.outputs.tag }}

    - name: ACS image scan
      run: |
          ./roxctl image check --endpoint "$STACKROX_CENTRAL_HOST:443" --image $QUAY_IO_REPOSITORY:${{ steps.set-tag.outputs.tag }} --insecure-skip-tls-verify || exit 1

    - name: Remove vulnerable Image
      if: failure()
      run: |
          sudo skopeo login --username $QUAY_IO_USERNAME --password "$QUAY_IO_PASSWORD" quay.io
          sudo skopeo delete docker://$QUAY_IO_REPOSITORY:${{ steps.set-tag.outputs.tag }}
