name: build

on:
  push:
    branches: ["main"]

env:
  STACKROX_CENTRAL_HOST: central-stackrox.apps.cluster-4r74v.4r74v.sandbox2251.opentlc.com
  ROX_API_TOKEN: ${{ secrets.ROX_API_TOKEN }}
  QUAY_IO_REPOSITORY: quay.io/doliveira1277/pipeline-acs
  QUAY_IO_USERNAME: ${{ secrets.QUAY_IO_USERNAME }}
  QUAY_IO_PASSWORD: ${{ secrets.QUAY_IO_PASSWORD }}

jobs:
  build-image:
    runs-on: ["ubuntu-24.04"]
    steps:
    - uses: actions/checkout@v3
    - name: install roxctl
      run: |
            curl -k -H "Authorization: Bearer $ROX_API_TOKEN" https://$STACKROX_CENTRAL_HOST:443/api/cli/download/roxctl-linux -o roxctl && chmod +x ./roxctl

    - name: set image tag
      id: set-tag
      run: |
          DATE=$(date +'%Y%m%d')
          TAG="${DATE}${GITHUB_RUN_NUMBER}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT    
    
    - name: Podman build image
      run: |
          podman build -t $QUAY_IO_REPOSITORY:${{ steps.set-tag.outputs.tag }} . -f app/Dockerfile

    - name: Podman push image
      run: |
          podman login -u="$QUAY_IO_USERNAME" -p="$QUAY_IO_PASSWORD" quay.io
          podman push $QUAY_IO_REPOSITORY:${{ steps.set-tag.outputs.tag }}

    - name: ACS image scan
      run: |
          ./roxctl image check --endpoint "$STACKROX_CENTRAL_HOST:443" --image $QUAY_IO_REPOSITORY:${{ steps.set-tag.outputs.tag }} --insecure-skip-tls-verify || exit 1

    - name: Remove vulnerable Image
      if: failure()
      run: |
          sudo skopeo login --username $QUAY_IO_USERNAME --password "$QUAY_IO_PASSWORD" quay.io
          sudo skopeo delete docker://$QUAY_IO_REPOSITORY:${{ steps.set-tag.outputs.tag }}
